--1. What is the total revenue generated by each
--sales representative?

SELECT s.name sales_rep,
      SUM(o.total_amt_usd) AS total_revenue
FROM sales_reps s
JOIN accounts a ON s.id = a.sales_rep_id
JOIN orders o ON a.id = o.account_id
GROUP BY s.name
ORDER BY total_revenue DESC

--2. How does customer region impact sales?

SELECT r.name region,
COUNT(o.id) AS total_sales
FROM region r
JOIN sales_reps s ON r.id = s.region_id
JOIN accounts a ON s.id = a.sales_rep_id
JOIN orders o ON a.id = o.account_id
GROUP BY r.name
ORDER BY total_sales DESC

--3. Which sales representative have the highest 
--average deal size/ order value?

SELECT s.name sales_rep,
AVG(o.total_amt_usd) AS avg_order_value
FROM sales_reps s
JOIN accounts a ON s.id = a.sales_rep_id
JOIN orders o ON a.id = o.account_id
GROUP BY s.name
ORDER BY avg_order_value DESC
LIMIT 1

--4. How does the order volume vary over time 
--(e.g., by month or year)?

SELECT
EXTRACT(YEAR FROM o.occurred_at) AS order_year,
EXTRACT(MONTH FROM o.occurred_at) AS order_month,
COUNT(o.id) AS order_count
FROM orders o
GROUP BY order_year, order_month
ORDER BY order_year, order_month

--5. What is the number of customers across 
--regions?

SELECT r.name region,
COUNT(a.id) AS customer_count
FROM region r
JOIN sales_reps s ON r.id = s.region_id
JOIN accounts a ON s.id = a.sales_rep_id
GROUP BY r.name
ORDER BY customer_count DESC

--6. What is the most common route for customer
--integration?

SELECT w.channel,
COUNT(a.id) AS customer_count
FROM accounts a
JOIN web_events w ON a.id = w.account_id
GROUP BY channel
ORDER BY customer_count DESC

--7. What are the websites that got the most orders? 

SELECT A.website AS Website_visited,
       O.account_id AS Account_id, 
COUNT(O.account_id) AS Num_of_visitation
FROM accounts AS A
INNER JOIN orders AS O
ON A.id = O.account_id
GROUP BY O.account_id,A.website
ORDER BY Num_of_visitation desc



--8. How many times event was taken place for each
--website?

SELECT website,
       COUNT(account_id) AS num_events
FROM web_events 
LEFT JOIN accounts 
ON web_events.account_id = accounts.id 
GROUP BY website
ORDER BY num_events DESC





